better testing environment

diff --git a/sh/test-one b/sh/test-one
--- a/sh/test-one
+++ b/sh/test-one
@@ -1,10 +1,10 @@
 #! /bin/env sh
 
 verbose=no
-test_file=
+test_file=test-file-not-set
 
 for arg do
-  case arg in
+  case "$arg" in
     -v)        verbose=yes      ;;
     --verbose) verbose=yes      ;;
     *)         test_file="$arg" ;;
@@ -17,17 +17,24 @@ no_color="\033[0m"
 
 tmp="$(mktemp "/tmp/stderr-of-test-os-hw2-date-$(date)-pid-$$-rand-XXXXX")"
 
-printf "${green}Testing $test_file ...${no_color}"
 chmod +x "$test_file"
 
-if [ verbose = yes ]
-then printf "\n"; "$test_file"
-else "$test_file" > /dev/null 2> "$tmp"
-fi
-
-if [ $? != 0 ]
-then printf "${red}Failed${no_color}\n" ; cat "$tmp"
-else printf "${green}Passed${no_color}\n"
+if [ "$verbose" = yes ]
+then
+  handle="========"
+  printf "\n${green}${handle} Testing $test_file ${handle}${no_color}\n"
+  "$test_file"
+  if [ $? != 0 ]
+  then printf "${red}${handle}Test ${test_file} failed${handle}${no_color}\n\n"
+  else printf "${green}${handle}Test ${test_file} passed${handle}${no_color}\n\n"
+  fi
+else
+  printf "${green}Testing $test_file ... ${no_color}"
+  "$test_file" > /dev/null 2> "$tmp"
+  if [ $? != 0 ]
+  then printf "${red}Failed${no_color}\n" ; cat "$tmp"
+  else printf "${green}Passed${no_color}\n"
+  fi
 fi
 
 rm "$tmp"
